=== trinkmuetze/uml_parser/UML_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="UML">
	<!-- TYPES -->
	<xs:simpleType name="visibility">
		<xs:restriction base="xs:string">
			<xs:enumeration value="public"/>
			<xs:enumeration value="private"/>
			<xs:enumeration value="package"/>
			<xs:enumeration value="protected"/>
			<xs:enumeration value="derived"/>
			<xs:enumeration value="static"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="relation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="association"/>
			<xs:enumeration value="directed Association"/>
			<xs:enumeration value="reflexive association"/>
			<xs:enumeration value="aggregation"/>
			<xs:enumeration value="composition"/>
			<xs:enumeration value="realization"/>
			<xs:enumeration value="inheritance"/>
		</xs:restriction>
	</xs:simpleType

	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="interface"/>
			<xs:enumeration value="abstract"/>
		</xs:restriction>
	</xs:simpleType>
<!------------------------------------------------------------------------------------------------------>
<!-- PACKAGE -->
	<xs:element name="package">
		<xs:simpleType>
			<xs:sequence>
				<xs:attribute name="name" type="xs:string" use="required" />
				<!-- CLASS -->
				<xs:element name="class">
					<xs:complexType>
						<xs:sequence>
							<xs:attribute name="name" type="xs:string" use="required" />
							<xs:attribute name="type" type="xs:classType" />
							<!-- ATTRIBUTE -->
							<xs:element name="attribute" type="xs:string">
								<xs:complexType>
									<xs:sequence>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="visibility" type="xs:visibility" />
										<xs:attribute name="data-type" type="xs:string" use="required" />
										<xs:attribute name="default-value" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<!-- METHOD -->
							<xs:element name="method" type="xs:string">
								<xs:complexType>
									<xs:sequence>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="visibility" type="xs:visibility" />
										<xs:attribute name="return-type" type="xs:string" use="required" />
										<xs:element name="parameter" type="xs:string">
											<xs:simpleType>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="data-type" type="xs:string" use="required" />
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:element>

<!-- RELATIONSHIP -->
	<xs:element name="relationship">
		<xs:simpleType>
			<xs:attribute name="type" type="xs:relation" use="required" />
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="toClass" type="xs:string" use="required" />
		</xs:simpleType>
	</xs:element>

=== trinkmuetze/uml_parser/BeispielXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<UML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UML_Schema.xsd">
	<class name="Animal">
	  <attribute name="legs" visibility="private" data-type="integer" />
	  <attribute name="eyes" visibility="private" data-type="integer" />
	  <attribute name="weight" visibility="private" data-type="double" />
	  <method name="eat" visibility="public" return-type="void">
	    <parameter name="prey" data-type="Prey" />
	  </method>
	  <method name="sleep" visibility="public" return-type="void">
	    <parameter name="hour" data-type="Integer" />
	  </method>
	  <method name="sound" visibility="public" return-type="void" />
	</class>

	<class name="Bird">
	  <method name="fly" visibility="public" return-type="void">
	    <parameter name="pos" data-type="Position"/>
	  </method>
	</class>

	<relationship type="inheritance" class="Bird" toClass="Animal"/>

	<package name="creatures">
	  <packageClass name="Animal"/>
	  <packageClass name="Bird"/>
	</package>
</UML>
