=== trinkmuetze/uml_parser/xsd/UML_Object_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="uml_object">
    <xs:complexType>
			<xs:sequence>
      <!-- OBJECT -->
        <xs:element name="object" minOccurs="0" maxOccurs="9">
          <xs:complexType>
						<xs:sequence>
              <xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="type" type="xs:string" />
                  <xs:attribute name="value" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="class" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      <!-- LINK -->
        <xs:element name="link" minOccurs="0" maxOccurs="9">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="object" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="role" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="toObject" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="role" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

  </xs:element>
</xs:schema>

=== trinkmuetze/uml_parser/xml/bsp_object.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml_object xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="-../xsd/UML_Object_Schema.xsd">

  <object name="lieblingsgrieche" class="Restaurant">
    <attribute name="kategorie" type="Sterne" value="3"/>
    <attribute name="name" value="Platon"/>
  </object>
  <object class="Kellner">
    <attribute name="persAusweisNr" value="12345"/>
    <attribute name="gehalt" value="1500" type="EUR"/>
  </object>
  <object name="maren" class="Gast">
    <attribute name="status" value="KÃ¶nig"/>
    <attribute name="geldbetrag" value="300" type="EUR"/>
    <attribute name="hunger" value="true"/>
  </object>

  <link name="bedient">
    <object name="Kellner"/>
    <toObject name="maren"/>
  </link>

  <link>
    <object name="Kellner" role="Arbeitnehmer"/>
    <toObject name="lieblingsgrieche" role="Arbeitgeber"/>
  </link>

</uml_object>
