=== trinkmuetze/uml_parser/xsd/UML_Deployment_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- TYPES -->
  <!-- ARTIFACT -->
  <xs:complexType name="artifact">
    <xs:attribute name="artifact_type" type="xs:string" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <!-- NODE -->
  <xs:complexType name="node">
    <xs:sequence>
      <xs:element name="node" type="node" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="artifact" type="artifact" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="node_type" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>


  <xs:element name="uml_deployment">
    <xs:complexType>
			<xs:sequence>
        <!-- NODE -->
        <xs:element name="node" type="node"  minOccurs="0" maxOccurs="unbounded" />
        <!-- ARTIFACT -->
        <xs:element name="artifact" type="artifact"  minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="relations"  minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <!-- NODE_NODE RELATION -->
              <xs:element name="node_node"  minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="node" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="multiplicity" type="xs:string" />
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="to_node" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="multiplicity" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" />
                </xs:complexType>
              </xs:element>

              <!-- ARTIFACT_NODE RELATION -->
              <xs:element name="artifact_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="artifact" type="xs:string" use="required" />
                  <xs:attribute name="to_node" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== trinkmuetze/uml_parser/xml/bsp_deployment.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml_deployment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="-../xsd/UML_Deployment_Schema.xsd">
  <node node_type="device" name="Zentralprozessor">
    <artifact name="Bildverarbeitung.exe" />
    <artifact name="Taskprogramm" />
    <artifact artifact_type="deployment spec" name="Bildaufbaubeschreibung.xml" />
  </node>

  <node node_type="device" name="Bildprozessor" />

  <artifact name="Strahlberechnungsprogramm" />

  <relations>
    <node_node name="Bildbearbeitung">
      <node name="Zentralprozessor" multiplicity="1" />
      <to_node name="Bildprozessor" multiplicity="1..*" />
    </node_node>

    <artifact_node artifact="Strahlberechnungsprogramm" to_node="Bildprozessor" />
  </relations>


</uml_deployment>
