=== trinkmuetze/uml_parser/xsd/UML_Component_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="uml_component">
    <xs:complexType>
			<xs:sequence>

          <!-- COMPONENT -->
          <xs:element name="component" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                  <xs:element name="provided_interface" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                  </xs:element>

                  <xs:element name="required_interface" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                  </xs:element>

                  <xs:element name="realization" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                  </xs:element>

                  <xs:element name="artifact" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                  </xs:element>

              </xs:sequence>
              <xs:attribute name="name" type="xs:string" />
            </xs:complexType>
          </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== trinkmuetze/uml_parser/xml/bsp_component.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml_component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="-../xsd/UML_Component_Schema.xsd">

  <component name="Projekte">
    <provided_interface name="Gesamtprojekt" />
    <provided_interface name="Einzelprojekt" />

    <required_interface name="Mitarbeiterzuordnung" />

    <realization name="Projektverwaltung" />
    <realization name="Projekt" />
    <realization name="Projektaufgabe" />
    <realization name="Projektkomponente" />
    <realization name="Einzelprojekte" />
    <realization name="Gesamtprojekte" />

    <artifact name="pm.jar" />
    <artifact name="gruenesProjekt.gif" />
    <artifact name="gelbesProjekt.gif" />
    <artifact name="rotesProjekt.gif" />
  </component>

</uml_component>
