=== trinkmuetze/uml_parser/xsd/UML_Class_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- TYPES -->
	<xs:simpleType name="visibility">
		<xs:restriction base="xs:string">
			<xs:enumeration value="+"/>
			<xs:enumeration value="-"/>
			<xs:enumeration value="~"/>
			<xs:enumeration value="/"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="relation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="association"/>
			<xs:enumeration value="aggregation"/>
			<xs:enumeration value="composition"/>
			<xs:enumeration value="inheritance"/>
			<xs:enumeration value="implementation"/>
			<xs:enumeration value="dependency"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="interface"/>
			<xs:enumeration value="abstract"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="multiplicity">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="0..1"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="1..1"/>
			<xs:enumeration value="0..*"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="1..*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="uml_class">
		<xs:complexType>
			<xs:sequence>
			<!-- PACKAGE -->
				<xs:element name="package">
					<xs:complexType>
						<xs:sequence>
							<!-- CLASS -->
							<xs:element name="class" minOccurs="0" maxOccurs="9">
								<xs:complexType>
									<xs:sequence>
										<!-- ATTRIBUTE -->
										<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="visibility" type="visibility" />
												<xs:attribute name="data-type" type="xs:string" use="required" />
												<xs:attribute name="default-value" type="xs:string" />
											</xs:complexType>
										</xs:element>
										<!-- METHOD -->
										<xs:element name="method" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required" />
															<xs:attribute name="data-type" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required" />
												<xs:attribute name="visibility" type="visibility" />
												<xs:attribute name="return-type" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="type" type="classType" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>

				<!-- RELATIONSHIP -->
				<xs:element name="relationship" minOccurs="0" maxOccurs="9">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="class">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="multiplicity" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="toClass">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="multiplicity" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" type="relation" use="required" />
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== trinkmuetze/uml_parser/xml/bsp_class.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml_class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="-../xsd/UML_Class_Schema.xsd">
	<package name="creatures">
		<class name="Animal">
  	  <attribute name ="legs" visibility="-" data-type="integer" />
  	  <attribute name="eyes" visibility="-" data-type="integer" />
  	  <attribute name="weight" visibility="-" data-type="double" />
  	  <method name="eat" visibility="+" return-type="void">
  	    <parameter name="prey" data-type="Prey" />
  	  </method>
  	  <method name="sleep" visibility="+" return-type="void">
  	    <parameter name="hour" data-type="Integer" />
  	  </method>
  	  <method name="sound" visibility="+" return-type="void" />
  	</class>

		<class name="Prey">
			<attribute name="legs" visibility="-" data-type="integer" />
			<attribute name="eyes" visibility="-" data-type="integer" />
			<attribute name="weight" visibility="-" data-type="double" />
			<method name="sleep" visibility="+" return-type="void">
				<parameter name="hour" data-type="Integer" />
			</method>
			<method name="sound" visibility="+" return-type="void" />
		</class>

		<class name="Jaguar">
			<method name="run" visibility="+" return-type="void">
				<parameter name="pos" data-type="Position"/>
				<parameter name="speed" data-type="Integer"/>
			</method>
		</class>

		<class name="Bird">
			<method name="fly" visibility="+" return-type="void">
				<parameter name="pos" data-type="Position"/>
				<parameter name="speed" data-type="Integer"/>
			</method>
		</class>

		<class name="Cat">
			<method name="run" visibility="+" return-type="void">
				<parameter name="pos" data-type="Position"/>
				<parameter name="speed" data-type="Integer"/>
			</method>
		</class>

		<class name="Dog">
			<attribute name="legs" visibility="-" data-type="integer" />
			<method name="run" visibility="+" return-type="void">
				<parameter name="pos" data-type="Position"/>
				<parameter name="speed" data-type="Integer"/>
			</method>
		</class>

	</package>

	<relation type="inheritance">
		<class name="Bird" multiplicity="1"/>
		<toClass name="Animal" multiplicity = "3"/>
	</relation>

	<relation type="inheritance">
		<class name="Cat" multiplicity="1"/>
		<toClass name="Animal"/>
	</relation>

	<relation type="implementation">
		<class name="Jaguar" multiplicity="1"/>
		<toClass name="Cat"/>
	</relation>

	<relation type="composition">
		<class name="Cat" multiplicity="1"/>
		<toClass name="Prey"/>
	</relation>

	<relation type="aggregation">
		<class name="Dog" multiplicity="24"/>
		<toClass name="Cat"/>
	</relation>
</uml_class>
